In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv("50_Startups.csv")

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
transfromed_X = ct.fit_transform(X)
X=transfromed_X

In [ ]:
type(X)

numpy.ndarray

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y,test_size=0.2, random_state=1)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [46]:
np.set_printoptions(precision=2)
y_predict=regressor.predict(X_test)




In [47]:
type(y_predict)

numpy.ndarray

In [48]:
print(y_predict)

[114664.42  90593.16  75692.84  70221.89 179790.26 171576.92  49753.59
 102276.66  58649.38  98272.03]


In [49]:
y_test

array([105008.31,  96479.51,  78239.91,  81229.06, 191050.39, 182901.99,
        35673.41, 101004.64,  49490.75,  97483.56])

In [51]:
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)), 1))

[[114664.42 105008.31]
 [ 90593.16  96479.51]
 [ 75692.84  78239.91]
 [ 70221.89  81229.06]
 [179790.26 191050.39]
 [171576.92 182901.99]
 [ 49753.59  35673.41]
 [102276.66 101004.64]
 [ 58649.38  49490.75]
 [ 98272.03  97483.56]]


In [53]:
print(regressor.coef_)
print(regressor.intercept_)


[-2.85e+02  2.98e+02 -1.24e+01  7.74e-01 -9.44e-03  2.89e-02]
49834.88507322592
